return {}

-- return {
--   {
--     "nyoom-engineering/oxocarbon.nvim",
--     lazy = false,
--     priority = 1000,
--     -- config = function()
--     --   -- Set the colorscheme
--     --   vim.cmd("colorscheme oxocarbon")
--     --
--     --   -- Make background transparent
--     -- end,
--   },
--   {
--     "LazyVim/LazyVim",
--     opts = {
--       colorscheme = "oxocarbon",
--       transparent = true,
--     },
--   },
-- }
